services:
  db:
    image: postgres:latest
    container_name: caixa_db_service
    restart: always
    environment:
      POSTGRES_USER: postgres 
      POSTGRES_PASSWORD: banco123 
      POSTGRES_DB: caixa_db # Opcional: use o valor fixo da API
      PORT: 3000
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql # Persistência de dados
    networks:
      - app-network

  api:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: caixa_api_service
    ports:
      - "3000:3000" # Porta da API
    depends_on:
      - db # Garante que o DB inicie antes
    environment:
      DB_HOST: db 
      DB_USER: postgres
      DB_PASSWORD: banco123
      DB_NAME: caixa_db
      PORT: 3000
    volumes:
      - ./backend:/app # Mapeia o código local para hot-reload
      - /app/node_modules # Evita que a pasta node_modules local sobrescreva a do container
    networks:
      - app-network
    # Inicia o servidor NestJS em modo de desenvolvimento (hot-reload)
    command: npm run start:dev

  client:

    image: node:20-alpine
    container_name: caixa_client_service
    working_dir: /app
    ports:
      - "5173:5173" # Porta padrão do Vite
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - app-network
    # Instala e executa o servidor de desenvolvimento do React/Vite
    command: sh -c "npm install && npm run dev"

# Volumes para persistência do DB
volumes:
  postgres_data:

# Rede para comunicação interna entre os serviços
networks:
  app-network:
    # Não precisa de driver, mas é boa prática