version: '3.8'

services:
  # Serviço do Backend (API)
  api:
    build:
      # O contexto é a pasta raiz
      context: . 
      # O Dockerfile que deve ser usado é o que está dentro da pasta backend/
      dockerfile: backend/Dockerfile 
    ports:
      - "3001:3000"
    restart: always

  # Serviço do Frontend (React)
  client:
    environment:
      - CHOKIDAR_USEPOLLING=true 
      - WDS_SOCKET_PORT=0 

    volumes:
      - ./frontend:/app
      - /app/node_modules
    build:
      # O contexto é a pasta raiz
      context: . 
      # O Dockerfile que deve ser usado é o que está dentro da pasta frontend/
      dockerfile: frontend/Dockerfile
    ports:
      - "80:80"
    depends_on:
      - api
    restart: always
    stdin_open: true  # Mantém o STDIN aberto (necessário para alguns servidores)
    tty: true 
    develop:
      watch:
        - action: sync
          paths:
            - ./frontend/src
            - ./frontend/public
          target: /app/src
          ignore:
            - node_modules/
        - action: rebuild
          path: package.json
            